image:
  name: "$CI_REGISTRY/zid/webinfo/docker-in-docker:latest"

stages:
  - build
  - deploy

#variables:
#   DOCKER_TLS_CERTDIR: "/root/.docker"
#   DOCKER_TLS_VERIFY: "1"
#   DOCKER_HOST: "tcp://138.232.16.180:2376"
#  TRAEFIK_HOST: "Host(`django-formset.awesto.com`)"

before_script:
  - mkdir -p $DOCKER_TLS_CERTDIR
  - echo "$CA" > $DOCKER_TLS_CERTDIR/ca.pem
  - echo "$CLIENT_CERT" > $DOCKER_TLS_CERTDIR/cert.pem
  - echo "$CLIENT_KEY" > $DOCKER_TLS_CERTDIR/key.pem

build_webapp:
  stage: build
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --squash
        --file .docker-files/webapp.dockerfile
        --tag $CI_REGISTRY_IMAGE
        --build-arg HTTP_PROXY --build-arg http_proxy
        --build-arg HTTPS_PROXY --build-arg https_proxy
        --build-arg NO_PROXY --build-arg no_proxy .
        --build-arg CI_COMMIT_TAG
        --build-arg CI_COMMIT_SHORT_SHA
        --build-arg CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - gitlab-demo
  except:
    changes:
      - "*.md"

deploy_webapp:
  stage: deploy
  environment:
    name: production
    url: https://django-formset.awesto.com
  variables:
    DOCKER_HOST: "tcp://138.232.16.180:2376"
    TRAEFIK_HOST: "Host(`django-formset.awesto.com`)"
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker stack deploy
        --compose-file .docker-files/compose.yml
        --with-registry-auth
        django-formset
  when: manual
  only:
    - gitlab-demo
  except:
    changes:
      - "*.md"
