name: Publish django-formset

on:
  push:
    tags:
      - '*'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    environment:
       name: deploy

    strategy:
      matrix:
        python-version: ["3.9"]
        node-version: ["14.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        npm install --also=dev
        python -m pip install --upgrade pip
        python -m pip install build --user
    - name: Build Parser
      run: npm run tag-attributes
    - name: Build Tailwind CSS
      run: npm run tailwindcss
    - name: Build Client
      run: |
        npm run build
        npm run uglify
    - name: Build 🐍 Python 📦 Package
      run: python -m build --sdist --wheel --outdir dist/
    - name: Publish 🐍 Python 📦 Package to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN_FORMSET }}
    - name: Deploy testapp to https://django-formset.fly.dev/
      uses: superfly/flyctl-actions/setup-flyctl@master
      run: flyctl deploy --remote-only
